apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: educationelly

bases:
  - ../../base

commonLabels:
  environment: production

images:
  - name: maxjeffwell/educationelly-server
    newTag: latest
  - name: maxjeffwell/educationelly-client
    newTag: latest
