apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: educationelly

resources:
  - namespace.yaml
  - configmap.yaml
  # Note: secret.example.yaml is not included - create actual secret manually
  - deployment-server.yaml
  - deployment-client.yaml
  - service-server.yaml
  - service-client.yaml
  - ingress.yaml
  - hpa-server.yaml
  - hpa-client.yaml
  - cluster-issuer.yaml

commonLabels:
  app: educationelly

images:
  - name: maxjeffwell/educationelly-server
    newTag: latest
  - name: maxjeffwell/educationelly-client
    newTag: latest
