apiVersion: v1
kind: Service
metadata:
  name: educationelly-client
  namespace: educationelly
  labels:
    app: educationelly
    component: client
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: educationelly
    component: client
  sessionAffinity: None
